apiVersion: v1
kind: Service
metadata:
  name: autopilot-micro
  namespace: autopilot
  labels:
    app: autopilot-micro
spec:
  selector:
    app: autopilot-micro
  ports:
    - name: http
      port: 3005
      targetPort: 3005
  type: ClusterIP
